apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-tmp-deployment
  labels:
    app: zookeeper-tmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-tmp
  template:
    metadata:
      labels:
        app: zookeeper-tmp
    spec:
      containers:
      - name: zookeeper
        #securityContext:
          #runAsUser: 1000
        image: bitnami/zookeeper
        env:
        - name: ZOO_MY_ID
          value: "1"
        - name: ZOO_ADMINSERVER_ENABLED
          valule: "true"
        ports:
        - containerPort: 2181
          name: tcp
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-tmp
  name: zookeeper-tmp
spec:
  ports:
  - name: tcp
    port: 2181
    protocol: TCP
    targetPort: tcp
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: zookeeper-tmp
  sessionAffinity: None
  type: ClusterIP
