#https://github.com/bitnami/bitnami-docker-zookeeper/blob/master/README.md
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-tmp-deployment
  labels:
    app: zookeeper-tmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-tmp
  template:
    metadata:
      labels:
        app: zookeeper-tmp
    spec:
      containers:
      - name: zookeeper
        #securityContext:
          #runAsUser: 1000
        image: bitnami/zookeeper
        env:
        - name: ZOO_MY_ID
          value: "1"
        - name: ZOO_ADMINSERVER_ENABLED
          value: "true"
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: ZOO_ENABLE_PROMETHEUS_METRICS
          value: "true"
        - name: ZOO_ENABLE_PROMETHEUS_METRICS
          value: "true"
        - name: ZOO_PROMETHEUS_METRICS_PORT_NUMBER
          value: "9090"
        ports:
        - containerPort: 2181
          name: tcp
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9090
          name: prom
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-tmp
  name: zookeeper-tmp
spec:
  ports:
  - name: tcp
    port: 2181
    protocol: TCP
    targetPort: tcp
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  - name: prom
    port: 9090
    targetPort: prom
  selector:
    app: zookeeper-tmp
  sessionAffinity: None
  type: ClusterIP
